---
- hosts: webservers
  user: vagrant
  sudo: True

  vars_files:
    - variables.yml

  tasks:
    - name: git checkout
      git: repo={{ repo_url }} dest=/var/www/{{ server_hostname }} accept_hostkey=yes
      sudo: False

    - name: update composer packages
      action: command /usr/bin/composer update chdir=/var/www/{{ server_hostname }}

    - name: ensure log directory
      action: file dest=/var/www/{{ server_hostname }}/app/logs/ state=directory owner=vagrant group=www-data mode=0775 recurse=yes

    - name: ensure cache directory
      action: file dest=/var/www/{{ server_hostname }}/app/cache/ state=directory mode=0775 owner=vagrant group=www-data recurse=yes