---
- name: Vagrant Ansible LEMP
  hosts: dev-server
  sudo: true
  user: vagrant

  vars_files:
    - vars_dev.yml

  roles:
    - common
    - ssh
    - php
    - composer
    - nginx
    - mysql
    - redis