---
- name: Vagrant Ansible LEMP
  hosts: webservers
  sudo: true
  user: {{ remote_user }}

  vars_files:
    - vars.yml

  roles:
    - common
    - ssh
    - php
    - composer
    - nginx
    - mysql