---
- name: Symfony with Vagrant-Ansible
  hosts: webservers
  sudo: yes
  user: vagrant

  vars_files:
    - vars.yml

  vars:
    user: vagrant

  roles:
    - common
    - ssh
    - git
    - php
    - composer
    - nginx
    - mysql