---
- name: Vagrant Ansible LEMP
  hosts: webservers
  sudo: true
  user: vagrant

  vars_files:
    - vars.yml

  vars:
    user: vagrant

  roles:
    - common
    - ssh
    - php
    - composer
    - nginx
    - mysql