---
- name: install nginx
  apt: pkg=nginx state=latest

- name: create nginx server configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: create nginx site configuration
  template: src=symfony.conf dest=/etc/nginx/sites-available/symfony.conf

- name: delete nginx default site configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: create nginx site configuration symlink
  file: src=/etc/nginx/sites-available/symfony.conf dest=/etc/nginx/sites-enabled/symfony.conf state=link
  notify: restart nginx
  