---
- name: install nginx
  apt: pkg=nginx state=latest

- name: create nginx main configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: create symfony nginx configuration
  template: src=symfony.conf dest=/etc/nginx/sites-available/symfony.conf

- name: delete default nginx configuration
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: create link for nginx configuration
  file: src=/etc/nginx/sites-available/symfony.conf dest=/etc/nginx/sites-enabled/symfony.conf state=link
  notify: restart nginx
  