---
- name: install mysql
  action: apt pkg={{ item }} state=present
  with_items:
    - mysql-server
    - python-dev
    - python-setuptools
    - python-mysqldb

- name: allow access to mysql from anywhere
  sudo: true
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" "line=#bind-address = 0.0.0.0"
  notify: restart mysql

- name: create mysql user
  mysql_user: name={{ database_user }} password={{ database_password }} priv={{ database_name }}.*:ALL state=present

- name: create mysql database
  mysql_db: name={{ database_name }} state=present
